require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("../models/Product");

const products = [
  {
    title: "Apple iPhone 16 Pro",
    brand: "Apple",
    category: "Smartphones",
    price: 134900,
    discountPercent: 5,
    rating: 4.7,
    reviewCount: 2318,
    stock: 42,
    description: "Apple's flagship smartphone with a titanium frame and pro-grade camera system.",
    longDescription: "The iPhone 16 Pro brings a refined titanium design, a brighter always-on display, and a significantly upgraded camera system built for both casual users and mobile photographers. Paired with Apple's latest chip, it handles everything from everyday multitasking to demanding creative work with ease.",
    features: [
      "6.3-inch Super Retina XDR display",
      "Titanium frame, lighter than previous generations",
      "Pro camera system with 5x telephoto zoom",
      "All-day battery life",
      "Action button and Camera Control",
      "Face ID for secure authentication",
    ],
    specifications: {
      Display: "6.3-inch OLED, 120Hz ProMotion",
      Processor: "A18 Pro chip",
      Storage: "256GB",
      RAM: "8GB",
      Battery: "3582 mAh",
      Camera: "48MP + 12MP + 12MP",
      OS: "iOS 18",
    },
    image: "",
    images: [],
    featured: true,
  },
  {
    title: "Samsung Galaxy S25 Ultra",
    brand: "Samsung",
    category: "Smartphones",
    price: 129999,
    discountPercent: 8,
    rating: 4.6,
    reviewCount: 1987,
    stock: 35,
    description: "Samsung's top-tier Android flagship with S Pen support and a 200MP main camera.",
    longDescription: "The Galaxy S25 Ultra combines a large, vibrant display with a versatile quad-camera setup and built-in S Pen support, making it a strong choice for productivity and photography alike. Its titanium build adds durability without adding bulk.",
    features: [
      "6.8-inch Dynamic AMOLED 2X display",
      "Built-in S Pen",
      "200MP main camera with 100x Space Zoom",
      "5000 mAh battery with fast charging",
      "IP68 water and dust resistance",
      "AI-powered photo editing tools",
    ],
    specifications: {
      Display: "6.8-inch AMOLED, 120Hz",
      Processor: "Snapdragon 8 Elite",
      Storage: "256GB",
      RAM: "12GB",
      Battery: "5000 mAh",
      Camera: "200MP + 50MP + 10MP + 12MP",
      OS: "Android 15, One UI 7",
    },
    image: "",
    images: [],
    featured: true,
  },
  {
    title: "Google Pixel 10 Pro",
    brand: "Google",
    category: "Smartphones",
    price: 99999,
    discountPercent: 10,
    rating: 4.5,
    reviewCount: 1203,
    stock: 28,
    description: "Google's AI-first smartphone with class-leading computational photography.",
    longDescription: "The Pixel 10 Pro focuses on a clean Android experience and industry-leading photo processing, powered by Google's own Tensor chip. It's an excellent choice for anyone who wants a great camera without needing to manually adjust settings.",
    features: [
      "6.7-inch LTPO OLED display",
      "Tensor G5 chip with on-device AI",
      "Triple rear camera with Magic Editor",
      "7 years of OS and security updates",
      "Fast wireless charging",
      "Always-on Assistant integration",
    ],
    specifications: {
      Display: "6.7-inch OLED, 120Hz",
      Processor: "Google Tensor G5",
      Storage: "128GB",
      RAM: "12GB",
      Battery: "4870 mAh",
      Camera: "50MP + 48MP + 48MP",
      OS: "Android 15",
    },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "OnePlus 13",
    brand: "OnePlus",
    category: "Smartphones",
    price: 69999,
    discountPercent: 12,
    rating: 4.4,
    reviewCount: 856,
    stock: 50,
    description: "A fast, fluid flagship with rapid charging and a Hasselblad-tuned camera.",
    longDescription: "The OnePlus 13 focuses on raw performance and speed — from its charging times to its touch responsiveness — while offering a Hasselblad camera partnership for solid photo quality at a more accessible flagship price.",
    features: [
      "6.82-inch AMOLED display",
      "100W fast wired charging",
      "Hasselblad-tuned triple camera",
      "Snapdragon flagship processor",
      "Large 6000 mAh battery",
      "Alert Slider for quick profile switching",
    ],
    specifications: {
      Display: "6.82-inch AMOLED, 120Hz",
      Processor: "Snapdragon 8 Gen 4",
      Storage: "256GB",
      RAM: "16GB",
      Battery: "6000 mAh",
      Camera: "50MP + 50MP + 50MP",
      OS: "Android 15, OxygenOS",
    },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "MacBook Air M4",
    brand: "Apple",
    category: "Laptops",
    price: 114900,
    discountPercent: 6,
    rating: 4.8,
    reviewCount: 3021,
    stock: 24,
    description: "Apple's thin-and-light laptop, now faster and more efficient with the M4 chip.",
    longDescription: "The MacBook Air M4 continues Apple's fanless, ultra-portable design while offering a meaningful performance jump for everyday productivity, light creative work, and long battery life — making it a strong pick for students and professionals on the move.",
    features: [
      "13.6-inch Liquid Retina display",
      "Fanless M4 chip design",
      "Up to 18 hours of battery life",
      "1080p FaceTime HD camera",
      "MagSafe charging",
      "Silent, fanless operation",
    ],
    specifications: {
      Display: "13.6-inch Retina",
      Processor: "Apple M4",
      RAM: "16GB",
      Storage: "512GB SSD",
      Battery: "Up to 18 hours",
      Weight: "1.24 kg",
      OS: "macOS Sequoia",
    },
    image: "",
    images: [],
    featured: true,
  },
  {
    title: "Dell XPS 13",
    brand: "Dell",
    category: "Laptops",
    price: 99990,
    discountPercent: 15,
    rating: 4.5,
    reviewCount: 1420,
    stock: 18,
    description: "A compact, premium Windows ultrabook with a virtually borderless display.",
    longDescription: "The Dell XPS 13 packs a large display into a small chassis thanks to its thin bezels, wrapped in a machined-aluminum body. It's built for professionals who want a premium, minimal laptop for everyday computing and light multitasking.",
    features: [
      "13.4-inch InfinityEdge display",
      "CNC-machined aluminum chassis",
      "Backlit keyboard with large trackpad",
      "Fast Wi-Fi 7 support",
      "Thunderbolt 4 ports",
      "Long battery life for all-day use",
    ],
    specifications: {
      Display: "13.4-inch FHD+",
      Processor: "Intel Core Ultra 7",
      RAM: "16GB",
      Storage: "512GB SSD",
      Battery: "Up to 13 hours",
      Weight: "1.17 kg",
      OS: "Windows 11",
    },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Lenovo Legion 5 Pro",
    brand: "Lenovo",
    category: "Laptops",
    price: 134990,
    discountPercent: 18,
    rating: 4.6,
    reviewCount: 967,
    stock: 15,
    description: "A powerful gaming laptop with a high-refresh QHD display and strong thermals.",
    longDescription: "The Legion 5 Pro is built for serious gaming and demanding workloads, pairing a high-refresh-rate QHD panel with a robust cooling system so performance stays consistent during long sessions.",
    features: [
      "16-inch QHD 165Hz display",
      "Dedicated gaming-grade GPU",
      "Legion Coldfront cooling system",
      "RGB backlit keyboard",
      "Fast SSD storage",
      "Multiple display and USB ports",
    ],
    specifications: {
      Display: "16-inch QHD, 165Hz",
      Processor: "AMD Ryzen 9",
      GPU: "Dedicated 8GB Graphics",
      RAM: "32GB",
      Storage: "1TB SSD",
      Weight: "2.4 kg",
      OS: "Windows 11",
    },
    image: "",
    images: [],
    featured: true,
  },
  {
    title: "Sony WH-1000XM6",
    brand: "Sony",
    category: "Headphones",
    price: 34990,
    discountPercent: 10,
    rating: 4.7,
    reviewCount: 2745,
    stock: 60,
    description: "Sony's flagship noise-cancelling headphones with refined comfort and sound.",
    longDescription: "The WH-1000XM6 continues Sony's reputation for class-leading active noise cancellation, paired with rich, detailed sound and an even more comfortable fit for long listening sessions, whether commuting or working.",
    features: [
      "Industry-leading active noise cancellation",
      "30-hour battery life",
      "Multipoint Bluetooth connection",
      "Touch sensor controls",
      "Adaptive Sound Control",
      "Foldable, travel-friendly design",
    ],
    specifications: {
      Type: "Over-ear, wireless",
      "Battery Life": "30 hours (ANC on)",
      Connectivity: "Bluetooth 5.3",
      Weight: "250g",
      Charging: "USB-C, fast charge",
    },
    image: "",
    images: [],
    featured: true,
  },
  {
    title: "Apple AirPods Pro (3rd Gen)",
    brand: "Apple",
    category: "Headphones",
    price: 24900,
    discountPercent: 5,
    rating: 4.6,
    reviewCount: 3980,
    stock: 80,
    description: "Apple's premium true wireless earbuds with adaptive noise control.",
    longDescription: "The 3rd generation AirPods Pro improve on fit, battery life, and noise cancellation, while adding deeper integration with Apple devices for seamless switching between iPhone, iPad, and Mac.",
    features: [
      "Active Noise Cancellation and Transparency mode",
      "Adaptive Audio",
      "Up to 6 hours of listening per charge",
      "Sweat and water resistant",
      "Wireless charging case",
      "Personalized spatial audio",
    ],
    specifications: {
      Type: "In-ear, true wireless",
      "Battery Life": "6 hours (ANC on), 30 hours with case",
      Connectivity: "Bluetooth 5.3",
      "Water Resistance": "IP54",
    },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Samsung Galaxy Watch Ultra",
    brand: "Samsung",
    category: "Smart Watches",
    price: 44999,
    discountPercent: 12,
    rating: 4.4,
    reviewCount: 612,
    stock: 22,
    description: "A rugged, feature-rich smartwatch built for fitness and outdoor tracking.",
    longDescription: "The Galaxy Watch Ultra is designed for active users, combining a durable titanium case with advanced health tracking, long battery life, and outdoor-focused features like route tracking and dive mode.",
    features: [
      "Titanium case with sapphire crystal glass",
      "Multi-day battery life",
      "Advanced health and sleep tracking",
      "Built-in GPS with route tracking",
      "100m water resistance",
      "Quick Button for instant access to workouts",
    ],
    specifications: {
      Display: "1.5-inch AMOLED",
      Battery: "Up to 100 hours (power saving)",
      Case: "Titanium, 47mm",
      "Water Resistance": "10ATM + IP68",
      Compatibility: "Android",
    },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Fitbit Sense 3",
    brand: "Fitbit",
    category: "Smart Watches",
    price: 22999,
    discountPercent: 15,
    rating: 4.3,
    reviewCount: 489,
    stock: 30,
    description: "A health-focused smartwatch with stress management and sleep tracking.",
    longDescription: "The Fitbit Sense 3 leans into wellness and recovery, offering continuous stress and heart health monitoring alongside detailed sleep insights, built for people who want to understand their body better day to day.",
    features: [
      "Continuous heart rate and stress tracking",
      "Advanced sleep score and insights",
      "6+ day battery life",
      "Built-in GPS",
      "Water resistant to 50m",
      "Guided breathing sessions",
    ],
    specifications: {
      Display: "AMOLED, always-on option",
      Battery: "Up to 6 days",
      "Water Resistance": "5ATM",
      Compatibility: "Android & iOS",
    },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Logitech G Pro X Superlight",
    brand: "Logitech",
    category: "Gaming Accessories",
    price: 12995,
    discountPercent: 8,
    rating: 4.8,
    reviewCount: 1654,
    stock: 45,
    description: "An ultra-lightweight wireless gaming mouse built for competitive play.",
    longDescription: "The G Pro X Superlight strips away unnecessary weight without sacrificing performance, giving competitive players a mouse that feels effortless during long sessions while maintaining pinpoint tracking accuracy.",
    features: [
      "Under 63 grams",
      "HERO 25K sensor",
      "LIGHTSPEED wireless technology",
      "70-hour battery life",
      "Zero-additive PTFE feet",
      "5 programmable buttons",
    ],
    specifications: {
      Sensor: "HERO 25K",
      Weight: "63g",
      Connectivity: "LIGHTSPEED Wireless",
      Battery: "Up to 70 hours",
      DPI: "Up to 25,600",
    },
    image: "",
    images: [],
    featured: true,
  },
  {
    title: "Razer BlackWidow V4",
    brand: "Razer",
    category: "Gaming Accessories",
    price: 15999,
    discountPercent: 10,
    rating: 4.5,
    reviewCount: 723,
    stock: 33,
    description: "A full-size mechanical gaming keyboard with per-key RGB lighting.",
    longDescription: "The BlackWidow V4 offers a sturdy, full-size typing and gaming experience with hot-swappable switches, dedicated media controls, and vibrant per-key lighting for a personalized setup.",
    features: [
      "Hot-swappable mechanical switches",
      "Per-key RGB lighting",
      "Dedicated multimedia roller and buttons",
      "Onboard memory profiles",
      "Magnetic wrist rest included",
      "Durable doubleshot keycaps",
    ],
    specifications: {
      "Switch Type": "Razer Mechanical (hot-swappable)",
      Lighting: "Per-key RGB",
      Connectivity: "Wired USB",
      "Extra Features": "USB passthrough, media controls",
    },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Canon EOS R50",
    brand: "Canon",
    category: "Cameras",
    price: 62999,
    discountPercent: 10,
    rating: 4.6,
    reviewCount: 445,
    stock: 12,
    description: "A compact mirrorless camera great for creators moving up from a phone camera.",
    longDescription: "The EOS R50 is designed to be approachable for beginners while still offering the image quality and autofocus performance creators need for both photos and video content, all in a lightweight body.",
    features: [
      "24.2MP APS-C sensor",
      "4K video recording",
      "Fast, reliable autofocus with subject tracking",
      "Vari-angle touchscreen",
      "Lightweight, compact body",
      "Built-in Wi-Fi and Bluetooth",
    ],
    specifications: {
      Sensor: "24.2MP APS-C CMOS",
      Video: "4K UHD up to 30fps",
      Autofocus: "Dual Pixel CMOS AF II",
      Screen: "Vari-angle touchscreen",
      Weight: "375g (body only)",
    },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "iPad Air M3",
    brand: "Apple",
    category: "Tablets",
    price: 71900,
    discountPercent: 7,
    rating: 4.7,
    reviewCount: 1298,
    stock: 27,
    description: "A powerful, lightweight tablet suited for both productivity and creative work.",
    longDescription: "The iPad Air M3 balances performance and portability, making it a strong option for note-taking, creative apps, and light video editing, especially when paired with the Apple Pencil and Magic Keyboard accessories.",
    features: [
      "11-inch Liquid Retina display",
      "M3 chip performance",
      "Apple Pencil Pro support",
      "All-day battery life",
      "Landscape stereo speakers",
      "Compatible with Magic Keyboard",
    ],
    specifications: {
      Display: "11-inch Liquid Retina",
      Processor: "Apple M3",
      Storage: "128GB",
      Battery: "Up to 10 hours",
      Weight: "460g",
      OS: "iPadOS 18",
    },
    image: "",
    images: [],
    featured: true,
  },
];

const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB connected for seeding");

    let insertedCount = 0;
    let skippedCount = 0;

    for (const productData of products) {
      const existing = await Product.findOne({ title: productData.title });
      if (existing) {
        skippedCount++;
        continue;
      }
      await Product.create(productData);
      insertedCount++;
    }

    console.log(`Seeding complete: ${insertedCount} product(s) added, ${skippedCount} already existed and were skipped.`);
    process.exit(0);
  } catch (error) {
    console.error("Seeding failed:", error.message);
    process.exit(1);
  }
};

seedProducts();