require("dotenv").config();
const mongoose = require("mongoose");
const Product = require("../models/Product");

// Maps old category names (from the earlier catalog checkpoint) to the new umbrella categories
const categoryMigrationMap = {
  Smartphones: "Electronics",
  Laptops: "Electronics",
  Tablets: "Electronics",
  Cameras: "Electronics",
  Headphones: "Audio",
  "Smart Watches": "Wearables",
  "Gaming Accessories": "Gaming",
};

const migrateCategories = async () => {
  let migratedCount = 0;
  for (const [oldCategory, newCategory] of Object.entries(categoryMigrationMap)) {
    const result = await Product.updateMany({ category: oldCategory }, { category: newCategory });
    migratedCount += result.modifiedCount;
  }
  return migratedCount;
};

const products = [
  // ---------- ELECTRONICS ----------
  {
    title: "Xiaomi 14 Ultra",
    brand: "Xiaomi",
    category: "Electronics",
    price: 89999,
    discountPercent: 10,
    rating: 4.4,
    reviewCount: 512,
    stock: 30,
    description: "A flagship Android phone with a Leica-tuned quad camera system.",
    features: ["6.73-inch AMOLED display", "Leica quad camera", "5300 mAh battery"],
    specifications: { Processor: "Snapdragon 8 Gen 3", RAM: "16GB", Storage: "512GB" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "ASUS ROG Zephyrus G14",
    brand: "ASUS",
    category: "Electronics",
    price: 149990,
    discountPercent: 12,
    rating: 4.6,
    reviewCount: 340,
    stock: 14,
    description: "A compact, powerful gaming laptop with excellent battery life for its class.",
    features: ["14-inch QHD 165Hz display", "Dedicated GPU", "Lightweight aluminum chassis"],
    specifications: { Processor: "AMD Ryzen 9", RAM: "32GB", Storage: "1TB SSD" },
    image: "",
    images: [],
    featured: true,
  },
  {
    title: "Amazon Kindle Paperwhite",
    brand: "Amazon",
    category: "Electronics",
    price: 13999,
    discountPercent: 15,
    rating: 4.6,
    reviewCount: 2140,
    stock: 55,
    description: "A glare-free e-reader with weeks of battery life, perfect for book lovers.",
    features: ["6.8-inch glare-free display", "Waterproof design", "Weeks of battery life"],
    specifications: { Storage: "16GB", Display: "300 ppi E-ink" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Sony Alpha a6400",
    brand: "Sony",
    category: "Electronics",
    price: 74999,
    discountPercent: 8,
    rating: 4.5,
    reviewCount: 289,
    stock: 10,
    description: "A compact mirrorless camera with fast, reliable autofocus for hybrid shooters.",
    features: ["24.2MP APS-C sensor", "0.02s autofocus", "Flip-up touchscreen"],
    specifications: { Video: "4K UHD", Weight: "403g" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Samsung Galaxy Tab S10",
    brand: "Samsung",
    category: "Electronics",
    price: 64999,
    discountPercent: 10,
    rating: 4.4,
    reviewCount: 178,
    stock: 20,
    description: "A large, vivid Android tablet suited for both entertainment and productivity.",
    features: ["11-inch AMOLED display", "S Pen included", "All-day battery"],
    specifications: { RAM: "8GB", Storage: "256GB" },
    image: "",
    images: [],
    featured: false,
  },

  // ---------- FASHION ----------
  {
    title: "Levi's 511 Slim Fit Jeans",
    brand: "Levi's",
    category: "Fashion",
    price: 3499,
    discountPercent: 20,
    rating: 4.4,
    reviewCount: 890,
    stock: 100,
    description: "Classic slim-fit denim jeans built for everyday comfort and durability.",
    features: ["Slim fit through hip and thigh", "Stretch denim fabric", "5-pocket styling"],
    specifications: { Material: "98% Cotton, 2% Elastane", Fit: "Slim" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Nike Air Force 1 '07",
    brand: "Nike",
    category: "Fashion",
    price: 8295,
    discountPercent: 5,
    rating: 4.7,
    reviewCount: 3200,
    stock: 80,
    description: "An iconic all-white leather sneaker with timeless everyday style.",
    features: ["Full-grain leather upper", "Encapsulated Air-Sole unit", "Rubber outsole"],
    specifications: { Material: "Leather", Closure: "Lace-up" },
    image: "",
    images: [],
    featured: true,
  },
  {
    title: "Adidas Essentials Hoodie",
    brand: "Adidas",
    category: "Fashion",
    price: 3299,
    discountPercent: 25,
    rating: 4.3,
    reviewCount: 640,
    stock: 90,
    description: "A soft, relaxed-fit fleece hoodie for everyday layering.",
    features: ["Brushed fleece fabric", "Kangaroo pocket", "Ribbed cuffs and hem"],
    specifications: { Material: "Cotton blend", Fit: "Regular" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "H&M Cotton Casual Shirt",
    brand: "H&M",
    category: "Fashion",
    price: 1499,
    discountPercent: 30,
    rating: 4.1,
    reviewCount: 410,
    stock: 120,
    description: "A breathable cotton shirt suited for both casual and semi-formal wear.",
    features: ["100% cotton", "Regular fit", "Button-down collar"],
    specifications: { Material: "Cotton", Fit: "Regular" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Zara Floral Summer Dress",
    brand: "Zara",
    category: "Fashion",
    price: 3990,
    discountPercent: 15,
    rating: 4.2,
    reviewCount: 265,
    stock: 45,
    description: "A lightweight floral dress designed for warm-weather occasions.",
    features: ["Flowy A-line silhouette", "Adjustable straps", "Lightweight fabric"],
    specifications: { Material: "Viscose blend", Length: "Midi" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Puma Velocity Nitro 3 Running Shoes",
    brand: "Puma",
    category: "Fashion",
    price: 7999,
    discountPercent: 18,
    rating: 4.5,
    reviewCount: 512,
    stock: 60,
    description: "Responsive running shoes built for daily training and long-distance comfort.",
    features: ["Nitro foam midsole", "Breathable mesh upper", "Durable rubber outsole"],
    specifications: { Material: "Mesh", Use: "Running" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Uniqlo Airism Crew Neck T-Shirt",
    brand: "Uniqlo",
    category: "Fashion",
    price: 990,
    discountPercent: 10,
    rating: 4.3,
    reviewCount: 780,
    stock: 200,
    description: "A moisture-wicking, quick-drying everyday basic t-shirt.",
    features: ["Airism moisture-wicking fabric", "Quick-dry technology", "Tagless design"],
    specifications: { Material: "Polyester blend", Fit: "Regular" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Woodland Leather Boots",
    brand: "Woodland",
    category: "Fashion",
    price: 4995,
    discountPercent: 12,
    rating: 4.4,
    reviewCount: 355,
    stock: 40,
    description: "Rugged leather boots built for outdoor durability and all-day comfort.",
    features: ["Genuine leather upper", "Cushioned insole", "Slip-resistant outsole"],
    specifications: { Material: "Leather", Closure: "Lace-up" },
    image: "",
    images: [],
    featured: false,
  },

  // ---------- GAMING ----------
  {
    title: "Sony PlayStation 5 Slim",
    brand: "Sony",
    category: "Gaming",
    price: 54990,
    discountPercent: 5,
    rating: 4.8,
    reviewCount: 1820,
    stock: 18,
    description: "Sony's current-generation console with ultra-fast loading and stunning visuals.",
    features: ["Ultra-high-speed SSD", "4K gaming support", "DualSense controller included"],
    specifications: { Storage: "1TB", Resolution: "Up to 4K" },
    image: "",
    images: [],
    featured: true,
  },
  {
    title: "Xbox Series X",
    brand: "Microsoft",
    category: "Gaming",
    price: 52990,
    discountPercent: 8,
    rating: 4.7,
    reviewCount: 1340,
    stock: 15,
    description: "Microsoft's most powerful console, built for 4K gaming at high frame rates.",
    features: ["12 teraflops of processing power", "Quick Resume for multiple games", "4K gaming at up to 120fps"],
    specifications: { Storage: "1TB SSD", Resolution: "Up to 4K" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Nintendo Switch OLED",
    brand: "Nintendo",
    category: "Gaming",
    price: 32999,
    discountPercent: 6,
    rating: 4.7,
    reviewCount: 980,
    stock: 25,
    description: "A vibrant hybrid console for gaming at home or on the go.",
    features: ["7-inch OLED screen", "Enhanced audio", "Detachable Joy-Con controllers"],
    specifications: { Storage: "64GB", Display: "OLED" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Sony DualSense Wireless Controller",
    brand: "Sony",
    category: "Gaming",
    price: 6490,
    discountPercent: 5,
    rating: 4.6,
    reviewCount: 720,
    stock: 70,
    description: "The official PS5 controller with adaptive triggers and haptic feedback.",
    features: ["Adaptive triggers", "Haptic feedback", "Built-in microphone"],
    specifications: { Connectivity: "Bluetooth / USB-C", Battery: "Rechargeable" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "SteelSeries Arctis Nova Pro",
    brand: "SteelSeries",
    category: "Gaming",
    price: 24999,
    discountPercent: 15,
    rating: 4.6,
    reviewCount: 310,
    stock: 20,
    description: "A premium wireless gaming headset with active noise cancellation.",
    features: ["Active noise cancellation", "Hot-swappable batteries", "High-fidelity audio drivers"],
    specifications: { Connectivity: "Wireless 2.4GHz", Battery: "Dual swappable" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "HyperX Alloy Origins Keyboard",
    brand: "HyperX",
    category: "Gaming",
    price: 8999,
    discountPercent: 10,
    rating: 4.5,
    reviewCount: 265,
    stock: 35,
    description: "A compact mechanical keyboard built with aircraft-grade aluminum.",
    features: ["HyperX mechanical switches", "Per-key RGB lighting", "Compact aluminum frame"],
    specifications: { "Switch Type": "Mechanical", Connectivity: "Wired USB-C" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Corsair Dark Core RGB Pro Mouse",
    brand: "Corsair",
    category: "Gaming",
    price: 7999,
    discountPercent: 12,
    rating: 4.4,
    reviewCount: 190,
    stock: 40,
    description: "A wireless gaming mouse with a high-precision sensor and Qi charging support.",
    features: ["18,000 DPI sensor", "Qi wireless charging compatible", "Customizable RGB lighting"],
    specifications: { Connectivity: "Wireless / Wired", DPI: "Up to 18,000" },
    image: "",
    images: [],
    featured: false,
  },

  // ---------- AUDIO ----------
  {
    title: "JBL Flip 6 Portable Speaker",
    brand: "JBL",
    category: "Audio",
    price: 9999,
    discountPercent: 20,
    rating: 4.5,
    reviewCount: 1450,
    stock: 55,
    description: "A rugged, waterproof portable speaker with powerful, punchy sound.",
    features: ["IP67 waterproof rating", "12 hours of playtime", "PartyBoost support"],
    specifications: { Battery: "12 hours", Connectivity: "Bluetooth 5.1" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Bose QuietComfort Ultra Earbuds",
    brand: "Bose",
    category: "Audio",
    price: 24900,
    discountPercent: 10,
    rating: 4.6,
    reviewCount: 620,
    stock: 30,
    description: "Premium noise-cancelling earbuds with immersive spatial audio.",
    features: ["World-class noise cancellation", "Immersive audio mode", "Up to 6 hours battery"],
    specifications: { Battery: "6 hours (24 with case)", Connectivity: "Bluetooth 5.3" },
    image: "",
    images: [],
    featured: true,
  },
  {
    title: "boAt Rockerz 450 Headphones",
    brand: "boAt",
    category: "Audio",
    price: 1499,
    discountPercent: 40,
    rating: 4.2,
    reviewCount: 8900,
    stock: 150,
    description: "An affordable, comfortable wireless headphone with punchy bass.",
    features: ["20 hours of playback", "40mm dynamic drivers", "Foldable design"],
    specifications: { Battery: "20 hours", Connectivity: "Bluetooth 5.0" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Marshall Emberton II Speaker",
    brand: "Marshall",
    category: "Audio",
    price: 12999,
    discountPercent: 8,
    rating: 4.6,
    reviewCount: 340,
    stock: 25,
    description: "A compact, iconic-looking speaker with rich, room-filling sound.",
    features: ["30+ hours of playtime", "IP67 water and dust resistance", "True stereophonic sound"],
    specifications: { Battery: "30+ hours", Connectivity: "Bluetooth 5.1" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Sennheiser Momentum 4 Headphones",
    brand: "Sennheiser",
    category: "Audio",
    price: 29990,
    discountPercent: 12,
    rating: 4.7,
    reviewCount: 410,
    stock: 18,
    description: "Audiophile-grade wireless headphones with exceptional battery life.",
    features: ["Up to 60 hours battery life", "Adaptive noise cancellation", "Premium comfort design"],
    specifications: { Battery: "60 hours", Connectivity: "Bluetooth 5.2" },
    image: "",
    images: [],
    featured: false,
  },

  // ---------- WEARABLES ----------
  {
    title: "Apple Watch Series 10",
    brand: "Apple",
    category: "Wearables",
    price: 41900,
    discountPercent: 5,
    rating: 4.7,
    reviewCount: 980,
    stock: 25,
    description: "Apple's thinnest, most advanced smartwatch with comprehensive health tracking.",
    features: ["Always-on Retina display", "Advanced health sensors", "Water resistant to 50m"],
    specifications: { Display: "OLED", Battery: "Up to 18 hours" },
    image: "",
    images: [],
    featured: true,
  },
  {
    title: "Amazfit Bip 5 Fitness Band",
    brand: "Amazfit",
    category: "Wearables",
    price: 5999,
    discountPercent: 25,
    rating: 4.2,
    reviewCount: 560,
    stock: 60,
    description: "An affordable fitness tracker with a large display and long battery life.",
    features: ["1.91-inch HD display", "120+ sport modes", "Up to 10 days battery life"],
    specifications: { Battery: "Up to 10 days", "Water Resistance": "5ATM" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Garmin Venu 3",
    brand: "Garmin",
    category: "Wearables",
    price: 44990,
    discountPercent: 10,
    rating: 4.6,
    reviewCount: 320,
    stock: 15,
    description: "A premium GPS smartwatch with advanced sleep and fitness coaching.",
    features: ["Built-in GPS", "Sleep coaching", "Up to 14 days battery life"],
    specifications: { Battery: "Up to 14 days", Display: "AMOLED" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Xiaomi Smart Band 9",
    brand: "Xiaomi",
    category: "Wearables",
    price: 2999,
    discountPercent: 15,
    rating: 4.3,
    reviewCount: 1250,
    stock: 100,
    description: "A slim, lightweight fitness band with essential health tracking.",
    features: ["1.62-inch AMOLED display", "150+ workout modes", "Up to 21 days battery life"],
    specifications: { Battery: "Up to 21 days", "Water Resistance": "5ATM" },
    image: "",
    images: [],
    featured: false,
  },

  // ---------- ACCESSORIES ----------
  {
    title: "American Tourister Laptop Backpack",
    brand: "American Tourister",
    category: "Accessories",
    price: 2499,
    discountPercent: 30,
    rating: 4.3,
    reviewCount: 890,
    stock: 80,
    description: "A durable, water-resistant backpack with a padded laptop compartment.",
    features: ["Fits laptops up to 15.6 inches", "Water-resistant fabric", "Multiple organizer pockets"],
    specifications: { Material: "Polyester", Capacity: "28L" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Anker 20000mAh Power Bank",
    brand: "Anker",
    category: "Accessories",
    price: 2999,
    discountPercent: 20,
    rating: 4.6,
    reviewCount: 2100,
    stock: 120,
    description: "A high-capacity power bank with fast charging for phones and tablets.",
    features: ["20,000mAh capacity", "18W fast charging", "Dual USB output"],
    specifications: { Capacity: "20,000mAh", Output: "18W" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Spigen Tough Armor Phone Case",
    brand: "Spigen",
    category: "Accessories",
    price: 1499,
    discountPercent: 10,
    rating: 4.5,
    reviewCount: 1580,
    stock: 200,
    description: "A rugged, shock-absorbing phone case with reinforced corner protection.",
    features: ["Military-grade drop protection", "Built-in kickstand", "Precise cutouts"],
    specifications: { Material: "Polycarbonate + TPU" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Belkin 65W USB-C Charger",
    brand: "Belkin",
    category: "Accessories",
    price: 2999,
    discountPercent: 15,
    rating: 4.4,
    reviewCount: 640,
    stock: 90,
    description: "A compact, fast-charging USB-C wall charger for phones and laptops.",
    features: ["65W fast charging", "Compact design", "Compatible with most USB-C devices"],
    specifications: { Output: "65W", Ports: "1x USB-C" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Skybags Laptop Messenger Bag",
    brand: "Skybags",
    category: "Accessories",
    price: 1899,
    discountPercent: 25,
    rating: 4.1,
    reviewCount: 340,
    stock: 55,
    description: "A sleek messenger bag designed for daily commutes with laptop protection.",
    features: ["Padded laptop sleeve", "Adjustable shoulder strap", "Multiple compartments"],
    specifications: { Material: "Polyester", Capacity: "Fits up to 15.6-inch laptop" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "Portronics Wireless Charging Pad",
    brand: "Portronics",
    category: "Accessories",
    price: 999,
    discountPercent: 30,
    rating: 4.2,
    reviewCount: 780,
    stock: 110,
    description: "A slim wireless charging pad compatible with all Qi-enabled devices.",
    features: ["10W fast wireless charging", "LED charging indicator", "Anti-slip surface"],
    specifications: { Output: "10W", Compatibility: "Qi-enabled devices" },
    image: "",
    images: [],
    featured: false,
  },

  // ---------- BOOKS ----------
  {
    title: "Atomic Habits",
    brand: "Random House",
    category: "Books",
    price: 599,
    discountPercent: 20,
    rating: 4.8,
    reviewCount: 15200,
    stock: 200,
    description: "A practical guide to building good habits and breaking bad ones.",
    features: ["Paperback edition", "Self-help / Personal development", "320 pages"],
    specifications: { Author: "James Clear", Pages: "320" },
    image: "",
    images: [],
    featured: true,
  },
  {
    title: "Clean Code",
    brand: "Pearson",
    category: "Books",
    price: 899,
    discountPercent: 10,
    rating: 4.6,
    reviewCount: 3400,
    stock: 80,
    description: "A handbook of agile software craftsmanship for writing better code.",
    features: ["Paperback edition", "Programming / Software Engineering", "464 pages"],
    specifications: { Author: "Robert C. Martin", Pages: "464" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "The Lean Startup",
    brand: "Portfolio",
    category: "Books",
    price: 549,
    discountPercent: 15,
    rating: 4.5,
    reviewCount: 4200,
    stock: 100,
    description: "How today's entrepreneurs use continuous innovation to build successful businesses.",
    features: ["Paperback edition", "Business / Entrepreneurship", "336 pages"],
    specifications: { Author: "Eric Ries", Pages: "336" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "The Alchemist",
    brand: "HarperOne",
    category: "Books",
    price: 399,
    discountPercent: 25,
    rating: 4.7,
    reviewCount: 20500,
    stock: 250,
    description: "A timeless fable about following your dreams and personal legend.",
    features: ["Paperback edition", "Fiction", "208 pages"],
    specifications: { Author: "Paulo Coelho", Pages: "208" },
    image: "",
    images: [],
    featured: true,
  },
  {
    title: "Rich Dad Poor Dad",
    brand: "Plata Publishing",
    category: "Books",
    price: 449,
    discountPercent: 20,
    rating: 4.6,
    reviewCount: 9800,
    stock: 180,
    description: "A perspective-shifting guide to personal finance and building wealth.",
    features: ["Paperback edition", "Business / Personal Finance", "224 pages"],
    specifications: { Author: "Robert Kiyosaki", Pages: "224" },
    image: "",
    images: [],
    featured: false,
  },
  {
        title: "Ikigai",
    brand: "Penguin",
    category: "Books",
    price: 399,
    discountPercent: 18,
    rating: 4.5,
    reviewCount: 6700,
    stock: 150,
    description: "The Japanese secret to a long and happy life, explored through real stories.",
    features: ["Paperback edition", "Self-help", "208 pages"],
    specifications: { Author: "Héctor García & Francesc Miralles", Pages: "208" },
    image: "",
    images: [],
    featured: false,
  },
  {
    title: "You Don't Know JS: Scope & Closures",
    brand: "O'Reilly",
    category: "Books",
    price: 699,
    discountPercent: 5,
    rating: 4.6,
    reviewCount: 1150,
    stock: 60,
     description: "The Japanese secret to a long and happy life, explored through real stories.",
    features: ["Paperback edition", "Self-help", "208 pages"],
    specifications: { Author: "Héctor García & Francesc Miralles", Pages: "208" },
    image: "",
    images: [],
    featured: false,
  },
  {
     title: "Sapiens: A Brief History of Humankind",
    brand: "Harper",
    category: "Books",
    price: 649,
    discountPercent: 15,
    rating: 4.7,
    reviewCount: 18300,
    stock: 200,
    description: "A sweeping narrative of humankind's history, from ancient humans to the present.",
    features: ["Paperback edition", "Non-fiction / History", "464 pages"],
    specifications: { Author: "Yuval Noah Harari", Pages: "464" },
    image: "",
    images: [],
    featured: true,
  },
];

const categoryImages = {
  Electronics: [
    "https://images.pexels.com/photos/20432893/pexels-photo-20432893.jpeg",
    "https://images.pexels.com/photos/163192/iphone-laptop-macbook-pen-163192.jpeg",
    "https://images.pexels.com/photos/8166409/pexels-photo-8166409.jpeg",
  ],
  Fashion: [
    "https://images.pexels.com/photos/3965545/pexels-photo-3965545.jpeg",
    "https://images.pexels.com/photos/11911863/pexels-photo-11911863.jpeg",
    "https://images.pexels.com/photos/20415614/pexels-photo-20415614.jpeg",
  ],
  Gaming: ["https://images.pexels.com/photos/7862505/pexels-photo-7862505.jpeg"],
  Audio: [
    "https://images.pexels.com/photos/7772548/pexels-photo-7772548.jpeg",
    "https://images.pexels.com/photos/30981655/pexels-photo-30981655.jpeg",
  ],
  Wearables: ["https://images.pexels.com/photos/11031515/pexels-photo-11031515.png"],
  Accessories: [
    "https://images.pexels.com/photos/7969093/pexels-photo-7969093.jpeg",
    "https://images.pexels.com/photos/5208781/pexels-photo-5208781.jpeg",
    "https://images.pexels.com/photos/5208307/pexels-photo-5208307.jpeg",
  ],
  Books: ["https://images.pexels.com/photos/35972719/pexels-photo-35972719.jpeg"],
};

const categoryCounters = {};
const assignImage = (category) => {
  const images = categoryImages[category] || [];
  if (images.length === 0) return "";
  const index = categoryCounters[category] || 0;
  categoryCounters[category] = index + 1;
  return images[index % images.length];
};

products.forEach((product) => {
  product.image = assignImage(product.category);
});

const seedProducts = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("MongoDB connected for seeding");

     const migratedCount = await migrateCategories();
    console.log(`Category migration: ${migratedCount} existing product(s) reclassified to the new categories.`);

    let insertedCount = 0;
    let skippedCount = 0;

   let updatedCount = 0;

    for (const productData of products) {
      const existing = await Product.findOne({ title: productData.title });
      if (existing) {
        if (!existing.image && productData.image) {
          existing.image = productData.image;
          await existing.save();
          updatedCount++;
        } else {
          skippedCount++;
        }
        continue;
      }
      await Product.create(productData);
      insertedCount++;
    }

    const productsWithoutImages = await Product.find({
      $or: [{ image: "" }, { image: { $exists: false } }],
    });
    console.log(`DEBUG: Found ${productsWithoutImages.length} product(s) with missing images.`);

    let backfilledCount = 0;
    for (const dbProduct of productsWithoutImages) {
      const newImage = assignImage(dbProduct.category);
      if (newImage) {
        dbProduct.image = newImage;
        await dbProduct.save();
        backfilledCount++;
      }
    }

    console.log(`Seeding complete: ${insertedCount} added, ${updatedCount} updated, ${skippedCount} unchanged, ${backfilledCount} backfilled with images directly from the database.`);
    process.exit(0);
  } catch (error) {
    console.error("Seeding failed:", error.message);
    process.exit(1);
  }
};

seedProducts();

  