import { Laptop, Shirt, Footprints, Watch, Headphones, Camera, Gamepad2, BookOpen } from "lucide-react";

export const products = [
  {
    id: 1,
    title: "Wireless ANC Headphones",
    category: "Electronics",
    price: 2499,
    originalPrice: 3499,
    discountPercent: 29,
    rating: 4.6,
    reviewCount: 312,
    isAIPick: true,
    icon: Headphones,
    description: "Immersive sound with active noise cancellation, built for long listening sessions whether you're commuting, working, or relaxing.",
    features: ["Active Noise Cancellation", "30-hour battery life", "Bluetooth 5.3", "Foldable design"],
    inStock: true,
  },
  {
    id: 2,
    title: "Everyday Running Shoes",
    category: "Footwear",
    price: 1899,
    originalPrice: 2499,
    discountPercent: 24,
    rating: 4.4,
    reviewCount: 187,
    isAIPick: false,
    icon: Footprints,
    description: "Lightweight cushioned shoes designed for daily runs and all-day comfort, with breathable mesh uppers.",
    features: ["Breathable mesh upper", "Shock-absorbing sole", "Non-slip grip", "Machine washable"],
    inStock: true,
  },
  {
    id: 3,
    title: "Slim Fit Cotton Shirt",
    category: "Fashion",
    price: 799,
    originalPrice: 999,
    discountPercent: 20,
    rating: 4.2,
    reviewCount: 94,
    isAIPick: false,
    icon: Shirt,
    description: "A wardrobe essential — soft, breathable cotton with a modern slim fit that works for both casual and semi-formal looks.",
    features: ["100% cotton", "Slim fit", "Machine washable", "Available in 5 colors"],
    inStock: true,
  },
  {
    id: 4,
    title: "Smart Fitness Watch",
    category: "Accessories",
    price: 3299,
    originalPrice: 3999,
    discountPercent: 18,
    rating: 4.7,
    reviewCount: 428,
    isAIPick: true,
    icon: Watch,
    description: "Track your workouts, heart rate, and sleep with a sleek smartwatch that keeps you connected all day.",
    features: ["Heart rate monitor", "7-day battery life", "Water resistant", "Sleep tracking"],
    inStock: true,
  },
  {
    id: 5,
    title: "Compact Coding Laptop",
    category: "Electronics",
    price: 42999,
    originalPrice: 46999,
    discountPercent: 9,
    rating: 4.5,
    reviewCount: 256,
    isAIPick: true,
    icon: Laptop,
    description: "A lightweight, powerful laptop built for developers on the go, with a fast processor and all-day battery life.",
    features: ["16GB RAM", "512GB SSD", "14-inch display", "10-hour battery"],
    inStock: true,
  },
  {
    id: 6,
    title: "Mirrorless Camera Body",
    category: "Electronics",
    price: 28999,
    originalPrice: 32999,
    discountPercent: 12,
    rating: 4.3,
    reviewCount: 143,
    isAIPick: false,
    icon: Camera,
    description: "A compact mirrorless camera body delivering crisp, professional-quality photos for creators and hobbyists alike.",
    features: ["24MP sensor", "4K video", "In-body stabilization", "Wi-Fi transfer"],
    inStock: false,
  },
  {
    id: 7,
    title: "Wireless Gaming Mouse",
    category: "Gaming",
    price: 1299,
    originalPrice: 1599,
    discountPercent: 19,
    rating: 4.5,
    reviewCount: 201,
    isAIPick: false,
    icon: Gamepad2,
    description: "Precision wireless mouse built for competitive gaming, with customizable buttons and ultra-low latency.",
    features: ["Low-latency wireless", "6 programmable buttons", "RGB lighting", "70-hour battery"],
    inStock: true,
  },
  {
    id: 8,
    title: "Bestselling Fiction Bundle",
    category: "Books",
    price: 599,
    originalPrice: 799,
    discountPercent: 25,
    rating: 4.8,
    reviewCount: 512,
    isAIPick: true,
    icon: BookOpen,
    description: "A curated bundle of three bestselling fiction titles, perfect for weekend reading or gifting.",
    features: ["3 paperback books", "Award-winning authors", "Gift-ready packaging"],
    inStock: true,
  },
];

export function getProductById(id) {
  return products.find((product) => product.id === Number(id));
}

export function getSimilarProducts(product, count = 4) {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, count);
}